# Generated by Django 2.1.2 on 2018-10-11 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Enter flight number', max_length=20, unique=True)),
                ('flight_duration', models.DurationField()),
                ('scheduled', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('price_economy', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price_business', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='FlightStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Location'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_set', to='flights.Location'),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.FlightStatus'),
        ),
    ]
