# Generated by Django 2.1.2 on 2018-10-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='iata',
            field=models.CharField(default='AAA', max_length=3),
            preserve_default=False,
        ),
    ]
