# Generated by Django 2.1.2 on 2018-10-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_location_iata'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='capacity',
            field=models.IntegerField(default=500),
        ),
    ]
