# Generated by Django 2.1.2 on 2018-10-27 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20181017_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
