# Generated by Django 2.1.2 on 2018-10-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_flight_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=500),
        ),
    ]
