# Generated by Django 2.1.2 on 2018-10-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20181027_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.DateTimeField(blank=True),
        ),
    ]
