# Generated by Django 2.1.2 on 2018-10-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20181019_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passenger_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_first_name',
            field=models.CharField(default='Income', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_last_name',
            field=models.CharField(default='Income', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger_first_name',
            field=models.CharField(default='Income', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger_last_name',
            field=models.CharField(default='Income', max_length=100),
            preserve_default=False,
        ),
    ]
