# Generated by Django 2.1.2 on 2018-10-27 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(default='08066505627', max_length=11, validators=[django.core.validators.RegexValidator(message='Please enter a Nigerian mobile phone number', regex='^0\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='08066505627', max_length=11, validators=[django.core.validators.RegexValidator(message='Please enter a Nigerian mobile phone number', regex='^0\\d{10}$')]),
            preserve_default=False,
        ),
    ]
