# Generated by Django 2.1.2 on 2018-10-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20181027_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='passenger_dob',
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger_age',
            field=models.PositiveSmallIntegerField(default=40),
            preserve_default=False,
        ),
    ]
