# Generated by Django 2.1.2 on 2018-10-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20181027_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.BookingStatus'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_class',
            field=models.CharField(choices=[('E', 'economy'), ('B', 'business')], max_length=1),
        ),
    ]
