# Generated by Django 2.1.2 on 2018-10-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20181028_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business')], max_length=10),
        ),
    ]
